# ===================================
#  Column Definitions
# ===================================

columns:
    name: Name
    created_at:
        label: Date Created
        type: datetime
    updated_at:
        label: Last Modified
        type: timesince
